services:
  frontend:
    build:
      context: ./
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/myreactdd/backend
    ports:
      - "8000:8000"