FROM python:alpine3.19

WORKDIR /myreactdd/backend

COPY requirements.txt /myreactdd/backend/

RUN pip install -r requirements.txt

COPY . /myreactdd/backend

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]